In [2]:
import pandas as pd
import numpy as np

In [39]:
column_names = ['userId', 'movieId', 'rating', 'timestamp']
rating_df = pd.read_csv('u.data', sep='\t', names=column_names)

rating_df.drop(columns=['timestamp'], inplace=True)
rating_df

userId  movieId  rating
0         196      242       3
1         186      302       3
2          22      377       1
3         244       51       2
4         166      346       1
...       ...      ...     ...
99995     880      476       3
99996     716      204       5
99997     276     1090       1
99998      13      225       2
99999      12      203       3

[100000 rows x 3 columns]

In [40]:
import pandas as pd
colName = ["movieId", "title", "Release Date", "Video Release Date",
           "IMDb URL", "Unknown", "Action", "Adventure", "Animation",
           "Children's", "Comedy", "Crime", "Documentary", "Drama", "Fantasy",
           "Film-Noir", "Horror", "Musical", "Mystery", "Romance", "Sci-Fi",
           "Thriller", "War", "Western"]

movies_df = pd.read_csv("u.item", sep="|", encoding="iso-8859-1",  names=colName)
movies_df.drop(columns= ["Release Date", "Video Release Date",
           "IMDb URL", "Unknown", "Action", "Adventure", "Animation",
           "Children's", "Comedy", "Crime", "Documentary", "Drama", "Fantasy",
           "Film-Noir", "Horror", "Musical", "Mystery", "Romance", "Sci-Fi",
           "Thriller", "War", "Western"], inplace=True)

In [41]:
movies_df

movieId                                      title
0           1                           Toy Story (1995)
1           2                           GoldenEye (1995)
2           3                          Four Rooms (1995)
3           4                          Get Shorty (1995)
4           5                             Copycat (1995)
...       ...                                        ...
1677     1678                          Mat' i syn (1997)
1678     1679                           B. Monkey (1998)
1679     1680                       Sliding Doors (1998)
1680     1681                        You So Crazy (1994)
1681     1682  Scream of Stone (Schrei aus Stein) (1991)

[1682 rows x 2 columns]

In [44]:
movies_df.head()

movieId              title
0        1   Toy Story (1995)
1        2   GoldenEye (1995)
2        3  Four Rooms (1995)
3        4  Get Shorty (1995)
4        5     Copycat (1995)

In [45]:
rating_df.head()

userId  movieId  rating
0     196      242       3
1     186      302       3
2      22      377       1
3     244       51       2
4     166      346       1

In [46]:
df = pd.merge(rating_df,movies_df,on='movieId')
df.head()

userId  movieId  rating         title
0     196      242       3  Kolya (1996)
1      63      242       3  Kolya (1996)
2     226      242       5  Kolya (1996)
3     154      242       3  Kolya (1996)
4     306      242       5  Kolya (1996)

In [47]:
combine_movie_rating = df.dropna(axis = 0, subset = ['title'])
movie_ratingCount = (combine_movie_rating.
     groupby(by = ['title'])['rating'].
     count().
     reset_index().
     rename(columns = {'rating': 'totalRatingCount'})
     [['title', 'totalRatingCount']]
    )
movie_ratingCount.head()


title  totalRatingCount
0  'Til There Was You (1997)                 9
1               1-900 (1994)                 5
2      101 Dalmatians (1996)               109
3        12 Angry Men (1957)               125
4                 187 (1997)                41

In [48]:
rating_with_totalRatingCount = combine_movie_rating.merge(movie_ratingCount, left_on = 'title', right_on = 'title', how = 'left')
rating_with_totalRatingCount.head()

userId  movieId  rating         title  totalRatingCount
0     196      242       3  Kolya (1996)               117
1      63      242       3  Kolya (1996)               117
2     226      242       5  Kolya (1996)               117
3     154      242       3  Kolya (1996)               117
4     306      242       5  Kolya (1996)               117

In [49]:
pd.set_option('display.float_format', lambda x: '%.3f' % x)
print(movie_ratingCount['totalRatingCount'].describe())

count   1664.000
mean      60.096
std       80.956
min        1.000
25%        7.000
50%       27.000
75%       80.250
max      583.000
Name: totalRatingCount, dtype: float64


In [50]:
popularity_threshold = 50
rating_popular_movie= rating_with_totalRatingCount.query('totalRatingCount >= @popularity_threshold')
rating_popular_movie.head()

userId  movieId  rating         title  totalRatingCount
0     196      242       3  Kolya (1996)               117
1      63      242       3  Kolya (1996)               117
2     226      242       5  Kolya (1996)               117
3     154      242       3  Kolya (1996)               117
4     306      242       5  Kolya (1996)               117

In [65]:
rating_popular_movie.shape
rating_popular_movie

userId  movieId  rating               title  totalRatingCount
0         196      242       3        Kolya (1996)               117
1          63      242       3        Kolya (1996)               117
2         226      242       5        Kolya (1996)               117
3         154      242       3        Kolya (1996)               117
4         306      242       5        Kolya (1996)               117
...       ...      ...     ...                 ...               ...
97646     629      881       3  Money Talks (1997)                92
97647     126      881       5  Money Talks (1997)                92
97648     801      881       3  Money Talks (1997)                92
97649     889      881       3  Money Talks (1997)                92
97650     880      881       4  Money Talks (1997)                92

[84069 rows x 5 columns]

In [67]:
## First lets create a Pivot matrix

movie_features_df=rating_popular_movie.pivot_table(index='movieId',columns='userId',values='rating').fillna(0)
movie_features_df

userId    1     2     3     4     5     6     7     8     9     10   ...  \
movieId                                                              ...   
1       5.000 4.000 0.000 0.000 4.000 4.000 0.000 0.000 0.000 4.000  ...   
2       3.000 0.000 0.000 0.000 3.000 0.000 0.000 0.000 0.000 0.000  ...   
3       4.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000  ...   
4       3.000 0.000 0.000 0.000 0.000 0.000 5.000 0.000 0.000 4.000  ...   
5       3.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000  ...   
...       ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   
1065    0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000  ...   
1073    0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000  ...   
1074    0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000  ...   
1101    0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000  ...   
1119    0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000  ...   

userId    934   935   936   937   938   939   940   941   942   943  
movieId                                                              
1       2.000 3.000 4.000 0.000 4.000 0.000 0.000 5.000 0.000 0.000  
2       4.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 5.000  
3       0.000 0.000 4.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000  
4       5.000 0.000 0.000 0.000 0.000 0.000 2.000 0.000 0.000 0.000  
5       0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000  
...       ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  
1065    2.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000  
1073    0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000  
1074    0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 4.000  
1101    0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000  
1119    0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000  

[613 rows x 943 columns]

In [81]:
R = movie_features_df.values

In [68]:
from scipy.sparse import csr_matrix

movie_features_df_matrix = csr_matrix(movie_features_df.values)

from sklearn.neighbors import NearestNeighbors


model_knn = NearestNeighbors(metric = 'cosine', algorithm = 'brute')
model_knn.fit(movie_features_df_matrix)

NearestNeighbors(algorithm='brute', metric='cosine')

In [69]:
movie_features_df.shape
movie_features_df

userId    1     2     3     4     5     6     7     8     9     10   ...  \
movieId                                                              ...   
1       5.000 4.000 0.000 0.000 4.000 4.000 0.000 0.000 0.000 4.000  ...   
2       3.000 0.000 0.000 0.000 3.000 0.000 0.000 0.000 0.000 0.000  ...   
3       4.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000  ...   
4       3.000 0.000 0.000 0.000 0.000 0.000 5.000 0.000 0.000 4.000  ...   
5       3.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000  ...   
...       ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   
1065    0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000  ...   
1073    0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000  ...   
1074    0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000  ...   
1101    0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000  ...   
1119    0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000  ...   

userId    934   935   936   937   938   939   940   941   942   943  
movieId                                                              
1       2.000 3.000 4.000 0.000 4.000 0.000 0.000 5.000 0.000 0.000  
2       4.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 5.000  
3       0.000 0.000 4.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000  
4       5.000 0.000 0.000 0.000 0.000 0.000 2.000 0.000 0.000 0.000  
5       0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000  
...       ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  
1065    2.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000  
1073    0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000  
1074    0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 4.000  
1101    0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000  
1119    0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000  

[613 rows x 943 columns]

In [70]:
query_index = np.random.choice(movie_features_df.shape[0])
print(query_index)
query_index =2

29


In [93]:
distances, indices = model_knn.kneighbors(movie_features_df.iloc[query_index,:].values.reshape(1, -1), n_neighbors = 10)

In [94]:
movie_features_df.head()

userId    1     2     3     4     5     6     7     8     9     10   ...  \
movieId                                                              ...   
1       5.000 4.000 0.000 0.000 4.000 4.000 0.000 0.000 0.000 4.000  ...   
2       3.000 0.000 0.000 0.000 3.000 0.000 0.000 0.000 0.000 0.000  ...   
3       4.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000  ...   
4       3.000 0.000 0.000 0.000 0.000 0.000 5.000 0.000 0.000 4.000  ...   
5       3.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000  ...   

userId    934   935   936   937   938   939   940   941   942   943  
movieId                                                              
1       2.000 3.000 4.000 0.000 4.000 0.000 0.000 5.000 0.000 0.000  
2       4.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 5.000  
3       0.000 0.000 4.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000  
4       5.000 0.000 0.000 0.000 0.000 0.000 2.000 0.000 0.000 0.000  
5       0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000  

[5 rows x 943 columns]

In [95]:
print(distances, indices)

[[8.88178420e-16 5.47977091e-01 5.55644926e-01 5.76750654e-01
  5.95069684e-01 5.95212979e-01 5.95761367e-01 5.95919547e-01
  5.98324145e-01 6.02725889e-01]] [[  2 326 543  32  28 217  14 606 556 371]]


In [73]:
for i in range(0, len(distances.flatten())):
    if i == 0:
        print('Recommendations for {0}:\n'.format(movie_features_df.index[query_index]))
    else:
        print('{0}: {1}, with distance of {2}:'.format(i, movie_features_df.index[indices.flatten()[i]], distances.flatten()[i]))

Recommendations for 3:

1: 410, with distance of 0.5479770908614205:
2: 763, with distance of 0.5556449255906232:
3: 42, with distance of 0.5767506536400024:
4: 33, with distance of 0.5950696840258005:
5: 250, with distance of 0.5952129787633035:
6: 17, with distance of 0.5957613669019339:
7: 1047, with distance of 0.5959195470584193:
8: 825, with distance of 0.5983241452686641:
9: 475, with distance of 0.6027258891207252:
10: 235, with distance of 0.6031323752276752:
11: 249, with distance of 0.6086289493159707:
12: 240, with distance of 0.6102698758320326:
13: 67, with distance of 0.6119561475579:
14: 405, with distance of 0.6128776545188621:
15: 55, with distance of 0.6156640128977173:
16: 273, with distance of 0.6180153412500087:
17: 24, with distance of 0.6180900975017025:
18: 7, with distance of 0.6270793119804844:
19: 123, with distance of 0.6285254470050599:
20: 122, with distance of 0.6303749796863305:
21: 68, with distance of 0.6327779205034879:
22: 780, with distance of 0.63

In [76]:
import numpy as np


Rcap = movie_features_df.values



In [77]:
print(Rcap)

[[5. 4. 0. ... 5. 0. 0.]
 [3. 0. 0. ... 0. 0. 5.]
 [4. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 4.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [89]:
import math
def get_error(A,Rcap, R):
    return math.sqrt(np.sum((A * (R - Rcap)) ** 2) / np.sum(R))

In [90]:
A = R>0.5; A[A == True] = 1; A[A == False]   = 0; A = A.astype(np.float64, copy=False)

    

In [91]:
print(get_error(A,Rcap, R))

0.0
