# P ALS

In [1]:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:


import pandas as pd

with open('u.data', 'r') as file:
    # Read the lines of the file
    lines = file.readlines()

# Process the lines to create a list of tuples
data = []
for line in lines:
    parts = line.strip().split('\t')
    user_id = int(parts[0])
    item_id = int(parts[1])
    rating = int(parts[2])
    # Skip the timestamp (parts[3])
    data.append((user_id, item_id, rating))

# Create a DataFrame from the list of tuples
df = pd.DataFrame(data, columns=['userId', 'movieId', 'rating'])

# Print the first few rows of the DataFrame

df['movieId'].max()
df['movieId'].min()

temp = 1
userItem  = np.zeros((df['userId'].max()+1,df['movieId'].max()+1))
print(userItem )
print(userItem.shape)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(944, 1683)


In [3]:
for i in range (len(df['userId'])):
  userItem[df.userId[i]][df.movieId[i]] = df.rating[i]

print(userItem)
print(userItem.shape)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 5. 3. ... 0. 0. 0.]
 [0. 4. 0. ... 0. 0. 0.]
 ...
 [0. 5. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 5. ... 0. 0. 0.]]
(944, 1683)


In [4]:
R = userItem[1:]
print(R)
R = R[:, 1:]
print(R)

ep = [2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

[[0. 5. 3. ... 0. 0. 0.]
 [0. 4. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 5. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 5. ... 0. 0. 0.]]
[[5. 3. 4. ... 0. 0. 0.]
 [4. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [5. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 5. 0. ... 0. 0. 0.]]


In [5]:
A = R>0.5; A[A == True] = 1; A[A == False]   = 0; A = A.astype(np.float64, copy=False)

    

In [6]:
import matplotlib.pyplot as plt
import math



def runALS(A, R, n_factors, n_iterations, lambda_):
    '''
    Runs Alternating Least Squares algorithm in order to calculate matrix.

    :param A: User-Item Matrix with ratings
    :param R: User-Item Matrix with 1 if there is a rating or 0 if not
    :param n_factors: How many factors each of user and item matrix will consider
    :param n_iterations: How many times to run algorithm
    :param lambda_: Regularization parameter
    :return:
    '''
    print ("Initiating ")
    lambda_ = 0.1; n_factors = 3; n, m = A.shape; n_iterations = 20
    Users = 5 * np.random.rand(n, n_factors)
    Items = 5 * np.random.rand(n_factors, m)


    def get_error(A, Users, Items, R):
        # This calculates the MSE of nonzero elements
        return math.sqrt(np.sum((R * (A - np.dot(Users, Items))) ** 2) / np.sum(R))

    RMSE_List = []

    print ("Starting Iterations")
    for iter in range(n_iterations):
        for i, Ri in enumerate(R):
            Users[i] = np.linalg.solve(np.dot(Items, np.dot(np.diag(Ri), Items.T)) + lambda_ * np.eye(n_factors),
                                       np.dot(Items, np.dot(np.diag(Ri), A[i].T))).T
#             print('Users[i]',Users[i])
        print ("Error after solving for User Matrix:", get_error(A, Users, Items, R))

        for j, Rj in enumerate(R.T):
            Items[:,j] = np.linalg.solve(np.dot(Users.T, np.dot(np.diag(Rj), Users)) + lambda_ * np.eye(n_factors),
                                     np.dot(Users.T, np.dot(np.diag(Rj), A[:, j])))
        print ("Error after solving for Item Matrix:", get_error(A, Users, Items, R))

        RMSE_List.append(get_error(A, Users, Items, R))
        print ('%sth iteration is complete...' % iter)
        
    
    return Users,Items,RMSE_List.pop()
        

   

In [7]:
# import numpy as np
# R = np.array([[1,0,2,1],[4,5,1,0],[4,5,0,5],[4,1,0,6],[4,0,0,5]])
# A = R>0.5; A[A == True] = 1; A[A == False]   = 0; A = A.astype(np.float64, copy=False)

In [8]:
U,I,Rmse = runALS(R,A ,3, 40, 0.06)

Initiating 
Starting Iterations
Error after solving for User Matrix: 1.482928830661927
Error after solving for Item Matrix: 0.9160783500836644
0th iteration is complete...
Error after solving for User Matrix: 0.8857877267928586
Error after solving for Item Matrix: 0.8735911552744446
1th iteration is complete...
Error after solving for User Matrix: 0.8639140309514378
Error after solving for Item Matrix: 0.8567042960125935
2th iteration is complete...
Error after solving for User Matrix: 0.8505239896483978
Error after solving for Item Matrix: 0.8468101977185872
3th iteration is complete...
Error after solving for User Matrix: 0.8439778886245174
Error after solving for Item Matrix: 0.8425511889371514
4th iteration is complete...
Error after solving for User Matrix: 0.8412171399671228
Error after solving for Item Matrix: 0.8405944172117766
5th iteration is complete...
Error after solving for User Matrix: 0.8398065474547178
Error after solving for Item Matrix: 0.8394673533005645
6th iterati

In [9]:
print(U.shape)
print(I.shape)
Rcap = U.dot(I)
print(Rcap)

(943, 3)
(3, 1682)
[[3.92006936 3.1114272  2.91437646 ... 1.7239003  2.23770338 2.67460958]
 [4.22693458 3.23582635 2.03281321 ... 1.95677744 3.03746916 2.28801621]
 [3.14724171 2.62093983 2.73302118 ... 1.28974101 1.4558458  2.15459362]
 ...
 [4.34423347 3.54883568 3.15847483 ... 1.83666372 2.35956595 2.6518684 ]
 [4.53305468 3.806792   2.21173219 ... 1.84958751 2.7466128  1.62878692]
 [3.72080241 3.28766321 4.15625521 ... 1.37687163 1.06768189 2.81738716]]


In [10]:
import numpy as np
np.savetxt('Rcap.csv', Rcap, delimiter=',')

In [11]:
import numpy as np

# Load the matrix from the CSV file
loaded_matrix = np.loadtxt('/home/23m1526/100K/Rcap.csv', delimiter=',')
print(loaded_matrix)

[[3.92006936 3.1114272  2.91437646 ... 1.7239003  2.23770338 2.67460958]
 [4.22693458 3.23582635 2.03281321 ... 1.95677744 3.03746916 2.28801621]
 [3.14724171 2.62093983 2.73302118 ... 1.28974101 1.4558458  2.15459362]
 ...
 [4.34423347 3.54883568 3.15847483 ... 1.83666372 2.35956595 2.6518684 ]
 [4.53305468 3.806792   2.21173219 ... 1.84958751 2.7466128  1.62878692]
 [3.72080241 3.28766321 4.15625521 ... 1.37687163 1.06768189 2.81738716]]


In [12]:
import numpy as np

def predRatings(user_item_matrix, Rcap, j, movies_df):
    def non_Rated_movie(user_item_matrix, j):
        zero_indices = np.where(user_item_matrix[:, j] == 0)[0]
        return zero_indices.tolist()

    def store_ratings_sorted(Rcap, zero_indices, j):
        ratings_dict = {}
        for i in zero_indices:
            rating = Rcap[i, j]
            ratings_dict[i] = rating
        sorted_ratings_dict = dict(sorted(ratings_dict.items(), key=lambda x: x[1], reverse=True))
        sorted_ratings_dict = dict(list(sorted_ratings_dict.items())[:20])
        return sorted_ratings_dict

    def get_movie_names(movies_df, top_20_ratings_dict):
        movie_names_dict = {}
        for key in top_20_ratings_dict.keys():
            movie_id = movies_df.loc[movies_df['movieId'] == key, 'title'].values[0]
            movie_names_dict[key] = movie_id
        return movie_names_dict

    zero_indices = non_Rated_movie(user_item_matrix, j)
    top_20_ratings_dict = store_ratings_sorted(Rcap, zero_indices, j)
    movie_names_dict = get_movie_names(movies_df, top_20_ratings_dict)

    return movie_names_dict

In [13]:
import pandas as pd
colName = ["movieId", "title", "Release Date", "Video Release Date",
           "IMDb URL", "Unknown", "Action", "Adventure", "Animation",
           "Children's", "Comedy", "Crime", "Documentary", "Drama", "Fantasy",
           "Film-Noir", "Horror", "Musical", "Mystery", "Romance", "Sci-Fi",
           "Thriller", "War", "Western"]

movies_df = pd.read_csv("u.item", sep="|", encoding="iso-8859-1",  names=colName)
movies_df.drop(columns= ["Release Date", "Video Release Date",
           "IMDb URL", "Unknown", "Action", "Adventure", "Animation",
           "Children's", "Comedy", "Crime", "Documentary", "Drama", "Fantasy",
           "Film-Noir", "Horror", "Musical", "Mystery", "Romance", "Sci-Fi",
           "Thriller", "War", "Western"], inplace=True)

In [14]:
movies_df

movieId                                      title
0           1                           Toy Story (1995)
1           2                           GoldenEye (1995)
2           3                          Four Rooms (1995)
3           4                          Get Shorty (1995)
4           5                             Copycat (1995)
...       ...                                        ...
1677     1678                          Mat' i syn (1997)
1678     1679                           B. Monkey (1998)
1679     1680                       Sliding Doors (1998)
1680     1681                        You So Crazy (1994)
1681     1682  Scream of Stone (Schrei aus Stein) (1991)

[1682 rows x 2 columns]

In [17]:
p = predRatings(R,Rcap,25,movies_df)

In [18]:
p

{518: "Miller's Crossing (1990)",
 809: 'Rising Sun (1993)',
 687: "McHale's Navy (1997)",
 476: 'First Wives Club, The (1996)',
 848: 'Murder, My Sweet (1944)',
 807: 'Poetic Justice (1993)',
 340: 'Boogie Nights (1997)',
 172: 'Empire Strikes Back, The (1980)',
 564: 'Tales from the Hood (1995)',
 354: 'Wedding Singer, The (1998)',
 938: 'Smile Like Yours, A (1997)',
 35: 'Free Willy 2: The Adventure Home (1995)',
 922: 'Dead Man (1995)',
 117: 'Rock, The (1996)',
 731: 'Corrina, Corrina (1994)',
 413: 'Tales from the Crypt Presents: Bordello of Blood (1996)',
 927: 'Flower of My Secret, The (Flor de mi secreto, La) (1995)',
 696: 'City Hall (1996)',
 769: 'Congo (1995)',
 273: 'Heat (1995)'}

In [13]:
ep = [2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
rmse_CALS = []

for ep in ep:
    rmse_CALS.append(Rmse)

print('The RMSE for different epsilons are', rmse_CALS)

The RMSE for different epsilons are [0.08052301958167798, 0.08052301958167798, 0.08052301958167798, 0.08052301958167798, 0.08052301958167798, 0.08052301958167798, 0.08052301958167798, 0.08052301958167798, 0.08052301958167798, 0.08052301958167798]


In [1]:
import csv

rmse_CALS =  [0.8301938214881543, 0.8301938214881543, 0.8301938214881543, 0.8301938214881543,
  0.8301938214881543, 0.8301938214881543, 0.8301938214881543, 0.8301938214881543, 0.8301938214881543, 0.8301938214881543]


csv_file_path = '/home/23m1526/output2.csv'



In [2]:
with open(csv_file_path, 'w', newline='') as csv_file:
    writer = csv.writer(csv_file)
    writer.writerow(['List Name', 'Values'])
    writer.writerow(['rmse_CALS'] + rmse_CALS)
